### ISSUE TITLE
Concurrent modification on async title refresh

### ISSUE THREAD

**Issue by andrei1058** [andrei1058/SidebarLib#35]
Newly implemented placeholders in title causes a concurrent exception:
```
[12:47:23 WARN]: Exception in thread "Craft Scheduler Thread - 79"
[12:47:23 WARN]: org.apache.commons.lang.UnhandledException: Plugin BedWars1058 v23.10-SNAPSHOT generated an exception while executing task 17
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.util.ConcurrentModificationException
        at java.base/java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:977)
        at java.base/java.util.LinkedList$ListItr.next(LinkedList.java:899)
        at com.andrei1058.bedwars.libs.sidebar.WrappedSidebar.applyLinePlaceholders(WrappedSidebar.java:135)
        at com.andrei1058.bedwars.libs.sidebar.WrappedSidebar.parsePlaceholders(WrappedSidebar.java:162)
        at com.andrei1058.bedwars.libs.sidebar.v1_8_R3.SidebarImpl$NarniaSidebarObjective.getDisplayName(SidebarImpl.java:82)
        at net.minecraft.server.v1_8_R3.PacketPlayOutScoreboardObjective.<init>(SourceFile:25)
        at com.andrei1058.bedwars.libs.sidebar.v1_8_R3.SidebarImpl$NarniaSidebarObjective.sendUpdate(SidebarImpl.java:96)
        at com.andrei1058.bedwars.libs.sidebar.WrappedSidebar.refreshTitle(WrappedSidebar.java:178)
        at com.andrei1058.bedwars.sidebar.SidebarService.lambda$refreshTitles$0(SidebarService.java:165)
        at java.base/java.util.HashMap.forEach(HashMap.java:1429)
        at com.andrei1058.bedwars.sidebar.SidebarService.refreshTitles(SidebarService.java:165)
        at com.andrei1058.bedwars.sidebar.thread.RefreshTitleTask.run(RefreshTitleTask.java:28)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 4 more
```

- Add possibility to use different collection types on placeholders to prevent async issues

**Comment by andrei1058** [comment]
fixed in #37 37
